#!/usr/bin/env node
/*
  White-label rebrand
  -------------------
  Applies a brand config to assets/js/brand.js, then rebuilds the site.

    node scripts/rebrand.mjs brand.config.json
    node scripts/rebrand.mjs brand.config.json --build

  This is the one command a buyer runs to turn FinHub into their own branded
  product: their name in the header, footer, favicon, page titles, structured
  data and accent colours - without touching any calculator logic.
*/
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

const __dir = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dir, "..");
const cfgPath = process.argv[2] ? resolve(process.cwd(), process.argv[2]) : join(ROOT, "brand.config.json");
const doBuild = process.argv.includes("--build");

if (!existsSync(cfgPath)) {
  console.error(`Brand config not found: ${cfgPath}`);
  console.error("Copy brand.config.json, edit it, then run: node scripts/rebrand.mjs brand.config.json --build");
  process.exit(1);
}

let cfg;
try {
  cfg = JSON.parse(readFileSync(cfgPath, "utf8"));
} catch (e) {
  console.error("Brand config is not valid JSON:", e.message);
  process.exit(1);
}

const fallback = {
  name: "FinHub",
  org: "FinHub Tools",
  url: "https://finhub.example.com",
  logoMark: "",
  theme: { accent: "#6366f1", accent2: "#16a34a" },
  footerBlurb: "Accurate, free and transparent finance calculators for investing, loans, retirement, savings and trading - built on published formulas with charts you can understand.",
  footerDisclaimer: "provides educational estimates for personal finance planning. Nothing here is financial, investment or tax advice. Figures are projections at the assumptions you choose and may not reflect actual returns or tax rules.",
  sales: {
    enabled: true,
    contactEmail: "you@example.com",
    contactWhatsapp: "",
    priceINR: "\u20B914,999",
    priceUSD: "$199",
    setupDays: "24 hours"
  }
};

const merge = (base, over) => {
  const out = { ...base, ...over };
  out.theme = { ...base.theme, ...(over && over.theme ? over.theme : {}) };
  out.sales = { ...base.sales, ...(over && over.sales ? over.sales : {}) };
  return out;
};

const b = merge(fallback, cfg);
for (const key of ["name", "org", "url"]) {
  if (!b[key] || typeof b[key] !== "string") {
    console.error(`brand config: "${key}" is required and must be a string`);
    process.exit(1);
  }
}

const q = (s) => JSON.stringify(String(s));
const out = `/*
  Generated by scripts/rebrand.mjs on ${new Date().toISOString()}.
  Edit brand.config.json and re-run the script instead of editing by hand.
*/
export const BRAND = {
  name: ${q(b.name)},
  org: ${q(b.org)},
  url: ${q(b.url)},
  logoMark: ${q(b.logoMark)},
  theme: {
    accent: ${q(b.theme.accent)},
    accent2: ${q(b.theme.accent2)}
  },
  footerBlurb: ${q(b.footerBlurb)},
  footerDisclaimer: ${q(b.footerDisclaimer)},
  sales: {
    enabled: ${b.sales.enabled ? "true" : "false"},
    contactEmail: ${q(b.sales.contactEmail)},
    contactWhatsapp: ${q(b.sales.contactWhatsapp)},
    priceINR: ${q(b.sales.priceINR)},
    priceUSD: ${q(b.sales.priceUSD)},
    setupDays: ${q(b.sales.setupDays)}
  }
};
`;

writeFileSync(join(ROOT, "assets", "js", "brand.js"), out, "utf8");
console.log(`Branded as "${b.name}" (${b.org}) - wrote assets/js/brand.js`);

if (doBuild) {
  const { spawnSync } = await import("node:child_process");
  const res = spawnSync(process.execPath, [join(ROOT, "build.js")], { cwd: ROOT, stdio: "inherit" });
  process.exit(res.status || 0);
} else {
  console.log("Run `npm run build` (or pass --build) to regenerate dist/.");
}
